CREATE TABLE `apps` (
  `APP_ID` VARCHAR(20) NOT NULL COMMENT '子系统编号',
  `APP_NAME` VARCHAR(50) DEFAULT NULL COMMENT '子系统名称',
  `APP_CODE` VARCHAR(40) DEFAULT NULL COMMENT '子系统代码',
  `APP_STATUS` CHAR(1) DEFAULT NULL COMMENT '状态',
  `CREATED_DATE` DATETIME DEFAULT NULL COMMENT '加入时间',
  `CREATED_BY` VARCHAR(41) DEFAULT NULL COMMENT '操作人',
  `APP_NOTE` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `LOGINPAGE_URL` VARCHAR(512) DEFAULT NULL COMMENT '登陆页地址',
  `HOMEPAGE_URL` VARCHAR(512) DEFAULT NULL COMMENT '主页地址',
  `APP_SSO` CHAR(1) DEFAULT '0' COMMENT '单用户登录：0--否；1---是',
  `APP_SID` VARCHAR(50) DEFAULT NULL COMMENT '存放appId md5的结果',
  `APP_TYPE_ID` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`APP_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=1638 COMMENT='应用子系统表';